title: Dr. Birgit Jankovic-Steiner
description: Dr. Birgit Jankovic-Steiner - Bestsellerautorin, Psychologin, ehemalige Gründerin der Hexenschule Wien, Expertin des neuen Systems nach IYSAK
social_media_share_image: /images/birgit_profil.jpg
disqus-identifier:
google-analytics: